# Generated by Django 4.2.6 on 2023-12-21 12:45

from django.db import migrations, models
import django.db.models.deletion
import school_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.TextField(verbose_name="Школьник")),
                ("student_year", models.TextField(verbose_name="Год обучения")),
                ("student_group", models.TextField(verbose_name="Класс")),
            ],
            options={
                "verbose_name": "Информация о школьнике",
                "verbose_name_plural": "Информация о школьниках",
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_name", models.TextField(verbose_name="Учитель")),
                ("teacher_edu", models.TextField(verbose_name="Образование учителя")),
                ("teacher_subject", models.TextField(verbose_name="Предмет учителя")),
            ],
            options={
                "verbose_name": "Информация об учителе",
                "verbose_name_plural": "Информация об учителях",
                "db_table": "teachers",
            },
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата занятия")),
                (
                    "mark",
                    models.IntegerField(
                        validators=[school_app.models.mark_validator],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.student",
                        verbose_name="Школьник",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.teacher",
                        verbose_name="Учитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Успеваемость школьника",
                "verbose_name_plural": "Успеваемость школьников",
                "db_table": "performance",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата занятия")),
                ("indicator", models.BooleanField(verbose_name="Посещение")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.student",
                        verbose_name="Школьник",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.teacher",
                        verbose_name="Учитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Посещения обучающегося",
                "verbose_name_plural": "Посещения обучающихся",
                "db_table": "attendance",
            },
        ),
    ]
